name: Sunburn
version: 0.4
description: Add sun damage to the game.
author: mikenon
main: me.cyberstalk.spoutplugin.sunburn.Sunburn
depend: [Spout]
commands:
  sunburn:
    description: The main command for Sunburn.
    usage: /sunburn <args>